version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Change this line to map port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: .
    ports:
      - "3000:3000"